# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a13744ee0afada76fd87c62810458dc8"
name = "Fitback"
handle = "fitback-3"
application_url = "https://country-weird-ampland-resort.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://fitback-size.myshopify.com/"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://country-weird-ampland-resort.trycloudflare.com/auth/callback",
  "https://country-weird-ampland-resort.trycloudflare.com/auth/shopify/callback",
  "https://country-weird-ampland-resort.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
