# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d959e3b05f5a0b80990424ba2b0a14d"
name = "Fitback"
handle = "fitback-5"
application_url = "https://veterinary-periodically-glow-nobody.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fitback-size.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://veterinary-periodically-glow-nobody.trycloudflare.com/auth/callback",
  "https://veterinary-periodically-glow-nobody.trycloudflare.com/auth/shopify/callback",
  "https://veterinary-periodically-glow-nobody.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
