[[extensions]]
type = "theme"  # Correct extension type
name = "Fitback"
handle = "fitback"

[[extensions.blocks]]
name = "Modal Button"
target = "section"
file_name = "blocks/modal_button.liquid"

[[extensions.blocks.assets]]
name = "modal.js"
type = "script"

[[extensions.blocks.assets]]
name = "modal.css"
type = "stylesheet"
